Recipe(
    id="ce26d40f-093d-4161-a3b8-73e1943a08c7",
    user_id="15bf499a-6666-4eb7-827d-c975532688f2",
    group_id="76357a1a-38ec-40d8-9c0a-5c19d38eb64d",
    household_id="567cbbf0-c883-4ffd-87c8-870c6d41ec07",
    name="White Bean & Mushroom Ragout",
    slug="white-bean-mushroom-ragout",
    image="no image",
    recipe_servings=4.0,
    recipe_yield_quantity=0.0,
    recipe_yield="",
    total_time="1 hour 10 minutes",
    prep_time="15 minutes",
    cook_time=None,
    perform_time="55 minutes",
    description="A flavorful saucy oven baked ragout with juicy roasted mushrooms and white beans. The addition of olives, lemon and rosemary gives this recipe a stand out flavor and there is minimal work involved. The ragout itself is vegan, but crumbled feta is the perfect topping if you don't need it to be dairy free.",
    recipe_category=[],
    tags=[
        {
            "id": "3d38be68-3d09-41f9-939c-d1ac4200c943",
            "groupId": "76357a1a-38ec-40d8-9c0a-5c19d38eb64d",
            "name": "White Bean Ragout",
            "slug": "white-bean-ragout",
        },
        {
            "id": "62218c9c-97ae-4435-aee5-377d2774eea8",
            "groupId": "76357a1a-38ec-40d8-9c0a-5c19d38eb64d",
            "name": "Vegetarian Ragout",
            "slug": "vegetarian-ragout",
        },
        {
            "id": "e4079f69-717d-442e-a218-dce99175b2e8",
            "groupId": "76357a1a-38ec-40d8-9c0a-5c19d38eb64d",
            "name": "Mushroom Ragout",
            "slug": "mushroom-ragout",
        },
    ],
    tools=[],
    rating=None,
    org_url="https://www.happyveggiekitchen.com/white-bean-mushroom-ragout/",
    recipe_ingredient=[],
    recipe_instructions=[],
    nutrition={
        "calories": "318",
        "carbohydrateContent": "34",
        "cholesterolContent": "11",
        "fatContent": "16",
        "fiberContent": "8",
        "proteinContent": "13",
        "saturatedFatContent": "4",
        "sodiumContent": "564",
        "sugarContent": "6",
        "transFatContent": None,
        "unsaturatedFatContent": "12",
    },
    assets=[],
    settings={
        "public": True,
        "showNutrition": True,
        "showAssets": True,
        "landscapeView": False,
        "disableComments": False,
        "locked": False,
    },
    date_added=datetime.datetime(2025, 10, 18, 0, 0),
    date_updated=datetime.datetime(
        2025, 10, 18, 23, 36, 3, 143053, tzinfo=datetime.timezone.utc
    ),
    created_at=datetime.datetime(
        2025, 10, 18, 23, 36, 3, 145157, tzinfo=datetime.timezone.utc
    ),
    updated_at=datetime.datetime(
        2025, 10, 18, 23, 36, 3, 145159, tzinfo=datetime.timezone.utc
    ),
    last_made=None,
    extras={},
    notes=[],
    comments=[],
    recipeIngredient=[
        {
            "quantity": 0.0,
            "unit": None,
            "food": None,
            "note": "3 tbsp olive oil",
            "display": "3 tbsp olive oil",
            "title": None,
            "originalText": None,
            "referenceId": "495f6179-dad6-4805-ac87-7bcd49ff1c90",
        },
        {
            "quantity": 0.0,
            "unit": None,
            "food": None,
            "note": "2 tsp balsamic vinegar",
            "display": "2 tsp balsamic vinegar",
            "title": None,
            "originalText": None,
            "referenceId": "a2352d2e-6a13-4e5b-9a80-86b8362d6373",
        },
        {
            "quantity": 0.0,
            "unit": None,
            "food": None,
            "note": "10 oz chestnut mushrooms (de-stemmed and wiped clean)",
            "display": "10 oz chestnut mushrooms (de-stemmed and wiped clean)",
            "title": None,
            "originalText": None,
            "referenceId": "160aba1e-9eb3-4613-ae6a-f75960161a67",
        },
        {
            "quantity": 0.0,
            "unit": None,
            "food": None,
            "note": "1 small red onion (sliced into half moon shapes)",
            "display": "1 small red onion (sliced into half moon shapes)",
            "title": None,
            "originalText": None,
            "referenceId": "f4b1bf60-42b3-46b6-b27b-fba31919d8f1",
        },
        {
            "quantity": 0.0,
            "unit": None,
            "food": None,
            "note": "4 cloves garlic (crushed)",
            "display": "4 cloves garlic (crushed)",
            "title": None,
            "originalText": None,
            "referenceId": "72c4adb3-e324-4b59-9fe6-752b03e490d9",
        },
        {
            "quantity": 0.0,
            "unit": None,
            "food": None,
            "note": "1/2 tsp ground cumin",
            "display": "1/2 tsp ground cumin",
            "title": None,
            "originalText": None,
            "referenceId": "34610f03-3a3a-4f51-8df8-56383a16208c",
        },
        {
            "quantity": 0.0,
            "unit": None,
            "food": None,
            "note": "1/2 tsp ground cinnamon",
            "display": "1/2 tsp ground cinnamon",
            "title": None,
            "originalText": None,
            "referenceId": "be594370-0854-4a09-a8ea-c5f363d66780",
        },
        {
            "quantity": 0.0,
            "unit": None,
            "food": None,
            "note": "1/2 cup Kalamata olives (chopped)",
            "display": "1/2 cup Kalamata olives (chopped)",
            "title": None,
            "originalText": None,
            "referenceId": "dc4f152e-5a97-490b-90d6-8ba50fee6487",
        },
        {
            "quantity": 0.0,
            "unit": None,
            "food": None,
            "note": "2 tsps fresh rosemary (chopped)",
            "display": "2 tsps fresh rosemary (chopped)",
            "title": None,
            "originalText": None,
            "referenceId": "c98db292-99bd-4703-a541-94d34c6a1631",
        },
        {
            "quantity": 0.0,
            "unit": None,
            "food": None,
            "note": "14 oz canned white beans (drained )",
            "display": "14 oz canned white beans (drained )",
            "title": None,
            "originalText": None,
            "referenceId": "bc96fc85-8a56-4c1d-abc3-dc23393c0641",
        },
        {
            "quantity": 0.0,
            "unit": None,
            "food": None,
            "note": "14 oz canned diced or chopped tomatoes",
            "display": "14 oz canned diced or chopped tomatoes",
            "title": None,
            "originalText": None,
            "referenceId": "3086d640-4dc4-455d-a96f-d5ee4b12197f",
        },
        {
            "quantity": 0.0,
            "unit": None,
            "food": None,
            "note": "1 lemon (for zesting and cutting into wedges)",
            "display": "1 lemon (for zesting and cutting into wedges)",
            "title": None,
            "originalText": None,
            "referenceId": "e69d12ee-d535-4b3c-918f-2aabc7f8d497",
        },
        {
            "quantity": 0.0,
            "unit": None,
            "food": None,
            "note": "1 handful chopped kale",
            "display": "1 handful chopped kale",
            "title": None,
            "originalText": None,
            "referenceId": "850fbd6f-9f50-42d7-b4da-249a987ff669",
        },
        {
            "quantity": 0.0,
            "unit": None,
            "food": None,
            "note": "1/3 cup crumbled feta cheese (optional topping)",
            "display": "1/3 cup crumbled feta cheese (optional topping)",
            "title": None,
            "originalText": None,
            "referenceId": "0239eca2-a9e8-42fa-b772-3c1655a30fb5",
        },
    ],
    recipeInstructions=[
        {
            "id": "241b9be8-777d-44ed-abda-54a925242e98",
            "title": "",
            "summary": "",
            "text": "Heat the oven to 200C / 400F.",
            "ingredientReferences": [],
        },
        {
            "id": "cbe4719e-0ea1-4380-8572-d732606f4ddb",
            "title": "",
            "summary": "",
            "text": "First, prepare the mushrooms and onions for roasting.Arrange the whole mushrooms and sliced onion in a wide shallow casserole dish. Try to keep the onions in their half-moon shapes rather than breaking up the individual slices, this will slow down their cooking time to align better with the mushrooms.The pan should be pretty much full, but still have the ingredients in one single layer. Drizzle with olive oil and balsamic vinegar. Add salt and pepper to taste.",
            "ingredientReferences": [],
        },
        {
            "id": "60d9c6bd-2304-472c-981d-d06e8a07128d",
            "title": "",
            "summary": "",
            "text": "Place in the oven for 20 minutes, or until the mushrooms are browned and reduced and the onions are soft and browning at the edges.",
            "ingredientReferences": [],
        },
        {
            "id": "be165ae2-23cc-4858-b293-8520f7e49430",
            "title": "",
            "summary": "",
            "text": "Next, we will add the garlic, rosemary and spices.Ensure you have everything measured out and ready to go, then remove the pan from the oven and very quickly mix in the garlic, rosemary, cumin and cinnamon. The residual heat in the pan will soften the garlic and bring out all the fragrances.",
            "ingredientReferences": [],
        },
        {
            "id": "44ea06f0-1e6d-4be5-9705-3a514a5718da",
            "title": "",
            "summary": "",
            "text": "Add the olives, canned tomatoes and white beans. Add a good amount of salt and pepper to taste. Mix through, cover, and place back in the oven for at 30 more minutes.",
            "ingredientReferences": [],
        },
        {
            "id": "db264f9a-2b90-4474-8c27-a4826d4cdec8",
            "title": "",
            "summary": "",
            "text": "Add the kale and zest about 1/3rd of the lemon into the pan (about one teaspoon of zest). Give it all a good stir, cover it up again and place back in the oven for 5 more minutes to give the kale a chance to soften up.You can then cut the lemon into wedges for serving.",
            "ingredientReferences": [],
        },
        {
            "id": "277af436-bf0b-453c-9796-e9cf86b12bc1",
            "title": "",
            "summary": "",
            "text": "Serve!Scatter with feta (if using) and add lemon wedges for squeezing, then serve with bread or cooked grains.",
            "ingredientReferences": [],
        },
    ],
)

